# Generated by Django 5.0.4 on 2024-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=15)),
            ],
        ),
    ]
